apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-web-hello-app
  namespace: argocd
spec:
  destination: https://kubernetes.default.svc
    
  project: default
  source:
    repoURL: https://github.com/AliciaC07/kubernetes.git
    targetRevision: HEAD
    path: k8s-web-hello