name: Docker-Hub

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  #schedule:
   # - cron: '0 2 * * 1-5'
  push:
    #branches: [ "main" ]
    # Publish semver tags as releases.
    #tags: none #[ 'v*.*.*' ]
  pull_request:
    #branches: [ "develop" ]
 
  workflow_dispatch:
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  #IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: aliciac07/kubernetes-k8s
  IMAGE_TAG: 1.0.${{ github.run_number }}
jobs:
  build-container:
     name: Build container
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Login to Docker-hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Build and push to Docker-hub
         uses: docker/build-push-action@v2
         with:
           context: ./k8s-web-hello
           push: true
           tags: ${{ env.IMAGE_NAME }}:latest, ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
       - uses: actions/checkout@v2
       - name: Find and Replace
         uses: jacobtomlinson/gha-find-replace@v2
         with:
           include: "./k8s-web-hello/testing.yaml"
           find: "aliciac07/k8s-web-hello"
           replace: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
       - name: Push changes
         uses: ad-m/github-push-action@v0.6.0
         with:
           github_token: ${{ secrets.GIT_TOKEN }}
           branch: ${{ github.ref }}
           